apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-deployment
  namespace: sample-cluster-namespace
  labels:
    app: sample-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-spring-boot-app
  template:
    metadata:
      labels:
        app: sample-spring-boot-app
    spec:
      containers:
        - name: will-change-later
          image: dawiddc/will-change-later
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app-entrypoint
  namespace: sample-cluster-namespace
spec:
  type: NodePort
  selector:
    app: sample-spring-boot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
